export const URL_CHAMPIONS = "http://ddragon.leagueoflegends.com/cdn/11.14.1/data/es_MX/champion.json"
export const URL_CHAMPIONS_SKILL = "https://ddragon.leagueoflegends.com/cdn/11.14.1/data/es_MX/champion/"
export const URL_CHAMPIONS_IMAGE = "https://ddragon.leagueoflegends.com/cdn/img/champion/loading/"
export const URL_CHAMPIONS_SPLASH = "http://ddragon.leagueoflegends.com/cdn/img/champion/splash/"
export const URL_CHAMPIONS_SKILL_IMG = "http://ddragon.leagueoflegends.com/cdn/11.14.1/img/spell/"
export const URL_CHAMPIONS_PASSIVE_IMG = "http://ddragon.leagueoflegends.com/cdn/11.14.1/img/passive/"